version: '3.8'

services:
  ollama-proxy:
    build: .
    image: jjb000000/ollama-proxy:latest
    ports:
      - "5002:5002"
    environment:
      - GOOGLE_API_KEYS=${GOOGLE_API_KEYS}
      - OPENROUTER_API_KEYS=${OPENROUTER_API_KEYS}
      - AKASH_API_KEYS=${AKASH_API_KEYS}
      - COHERE_API_KEYS=${COHERE_API_KEYS}
      - CODESTRAL_API_KEYS=${CODESTRAL_API_KEYS}
    restart: always
    container_name: ollama-proxy