name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3                            # 코드 체크아웃 :contentReference[oaicite:3]{index=3}

      - name: Set up QEMU (optional)
        uses: docker/setup-qemu-action@v2                      # 크로스 플랫폼 빌드 지원 :contentReference[oaicite:4]{index=4}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2                    # 멀티 플랫폼·캐시 향상 :contentReference[oaicite:5]{index=5}

      - name: Login to Docker Hub
        uses: docker/login-action@v3                           # Docker Hub 인증 :contentReference[oaicite:6]{index=6}
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4                      # 빌드 및 푸시 :contentReference[oaicite:7]{index=7}
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ollama-proxy:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/ollama-proxy:cache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/ollama-proxy:cache,mode=max
